// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "github.com/devprod-tech/webike_recomendations-Vitalya/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// GeoExternalAdapter is an autogenerated mock type for the GeoExternalAdapter type
type GeoExternalAdapter struct {
	mock.Mock
}

// SendToShared provides a mock function with given fields: outputMsg, shared
func (_m *GeoExternalAdapter) SendToShared(outputMsg models.GeoOutput, shared *models.RecommendationsMessage) {
	_m.Called(outputMsg, shared)
}

// NewGeoExternalAdapter creates a new instance of GeoExternalAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGeoExternalAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *GeoExternalAdapter {
	mock := &GeoExternalAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
