// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "github.com/devprod-tech/webike_recomendations-Vitalya/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// GeoPort is an autogenerated mock type for the GeoPort type
type GeoPort struct {
	mock.Mock
}

// Accept provides a mock function with given fields: msg
func (_m *GeoPort) Accept(msg models.AnalyticsMessage) models.GeoInput {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 models.GeoInput
	if rf, ok := ret.Get(0).(func(models.AnalyticsMessage) models.GeoInput); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Get(0).(models.GeoInput)
	}

	return r0
}

// NewGeoPort creates a new instance of GeoPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGeoPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *GeoPort {
	mock := &GeoPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
