// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "github.com/devprod-tech/webike_recomendations-Vitalya/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// ParsingExternalAdapter is an autogenerated mock type for the ParsingExternalAdapter type
type ParsingExternalAdapter struct {
	mock.Mock
}

// SendToShared provides a mock function with given fields: outputMsg, shared
func (_m *ParsingExternalAdapter) SendToShared(outputMsg models.ParsingOutput, shared *models.RecommendationsMessage) {
	_m.Called(outputMsg, shared)
}

// NewParsingExternalAdapter creates a new instance of ParsingExternalAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParsingExternalAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParsingExternalAdapter {
	mock := &ParsingExternalAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
